### ISSUE TITLE
[Improvement] PreferConnectionAffinity setting

### ISSUE THREAD

**Issue by MarkMpn** [MscrmTools/XrmToolBox#1021]
For best performance for multi-threaded plugins we need the PreferConnectionAffinity setting added to the config file to load balance requests across multiple front-end web servers. Unfortunately CrmServiceClient doesn’t allow setting this on a per-instance basis and it needs to be done globally in the config file.

Details at https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/sample-tpl-crmserviceclient

**Comment by MarkMpn** [comment]
May also be worth setting the options shown in the “Optimize Connection Settings” section of the code sample on that same page to avoid each tool that wants to use parallel connections having to do the same?

**Comment by MscrmTools** [comment]
I can add both.
Question : do you think this might have negative impact if for single thread operation?

**Comment by MattB-msft** [comment]
To help informing your decisions

The reason its not trivial to change for the connections in the CrmServiceClient, and the DataverseServiceClient is that it currently has roughly a 10-15% negative impact on SDK performance.

This is a consequence of the changes that have been made in the PowerPlatform over the last number of years with regards to how we scale Dataverse horizontally.

For many of the XrmToolbox scenarios which focus on metadata change,  disabling affinity can have significant downsides as we no longer commit metadata changes across all nodes in a scalegroup before returning the call.  Thus a commit of change in one call, followed by a query for the change or its impacts may result in an error on a subsequent call with affinity disabled.

Outside of metadata scenarios,
Each call to a new node in the cluster requires that node to now load the metadata for the environment your connecting and communicating with.  In the situation were there are 10 nodes per URL,  every call has a 1 in 10 chance of hitting a metadata load due to a cache roll, unless the volume of calls are very high.  As you would see in a data import scenario.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MarkMpn** [comment]
Thanks @MattB-msft, that's very helpful!

I guess the ideal scenario then would be able to toggle this setting so that it's turned on by default but tools could turn it off for a specific connection temporarily while doing data imports. Would it be feasible to add this as a writeable property in CrmServiceClient/DataverseServiceClient rather than only being able to set it at the app config level?

**Comment by MattB-msft** [comment]
Yes, both the dataverseclient and crmserviceclient have it as a connection level property that predate the changes in our infrastructure.  We removed the public property to keep folks out of trouble.  We left the app.config override as a few of our tools use it for import purposes.

We are discussing reenabling it with some updates to documentation to make sure folks understand clearly what the ramifications are and under what circumstances it should be utilized.  Similar to the guidance around ForceServerMetadataCacheConsistency property.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MattB-msft** [comment]
As a follow up to this,  we have decided to reexpose the property and have done so in the latest version of the dataverse client.  The crm service client change has been committed and will rollout with the next public push we do.

**Comment by MarkMpn** [comment]
That's great news, thanks for the update!

**Comment by MscrmTools** [comment]
@MattB-msft I cannot tell enough how much I appreciate you are following XrmToolBox repository and you help me/us providing the best suite of tools possible for dataverse users

**Comment by MscrmTools** [comment]
So we are waiting the next public bytes to enable these optimization feature. It will be a per connection basis and I guess we will expose a property in `ConnectionDetail` class to enable this property so that each tool can activate this on purpose.
As for the optimization from [the documentation](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/sample-tpl-crmserviceclient#code-listing), I guess we can add them directly without any impact

**Comment by MarkMpn** [comment]
I'm not sure a new `ConnectionDetail` property is need - the tool can set the new property directly on the `CrmServiceClient` it gets from the `ServiceClient` property or `GetCrmServiceClient(bool)` method.

**Comment by MscrmTools** [comment]
Correct! So nothing to do on this side

**Comment by MattB-msft** [comment]
Microsoft.CrmSdk.XrmTooling.CoreAssembly 9.1.0.79 is posted and includes this update.

**Comment by MscrmTools** [comment]
released!
