### ISSUE TITLE
Show assembly version

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1050]
It would be great to have a techy information showing the version or all related assembly.
Easer for debug etc finding problems... 

See FXB for an example.

![image](https://user-images.githubusercontent.com/2572253/124904076-eb690d00-dfe4-11eb-956f-9270f8bbc719.png)

Some code is here:
https://github.com/rappen/FetchXMLBuilder/blob/master/FetchXmlBuilder/Forms/About.cs

**Comment by MscrmTools** [comment]
Ah! My favourite contributor is back 💪 

This is something I can work on

**Comment by MscrmTools** [comment]
I don't have space in About form for now, so it will stand in Settings
![image](https://user-images.githubusercontent.com/10774317/132821122-15ec92f3-0ff2-4282-a5d7-453bad14ff62.png)

**Comment by rappen** [comment]
Nice! 😊

**Comment by MscrmTools** [comment]
Changed a bit your code to display File version instead of Assembly version which shows more relevant info (especially for Dataverse SDK version)

```
private ListViewItem GetListItem(AssemblyName a)
{
    var assembly = Assembly.Load(a);
    var fi = FileVersionInfo.GetVersionInfo(assembly.Location);

    var item = new ListViewItem(a.Name);
    item.SubItems.Add(fi.FileVersion.ToString());
    return item;
}
```

![image](https://user-images.githubusercontent.com/10774317/133042987-3a9db0f7-2d6d-44f9-8bde-52be3005a242.png)

This new code will be deployed with next version of XrmToolBox

**Comment by rappen** [comment]
That's awesome!
This is getting to all my tools 🙂
