### ISSUE TITLE
Can't connect PowerApps Dataverse

### ISSUE THREAD

**Issue by ilis18** [MscrmTools/XrmToolBox#1051]
**Describe the bug**
I have just installed the XrmToolBox and tried to connect Dataverse using "Connection String" and OAuth/MFA methods
The both ones failed. connection string that I used works OK when I connect my Power Apps environment from C# program

**To Reproduce**
connection string: 
AuthType=Office365;Url=https://[environment].crm3.dynamics.com;Username=ilya.lis@ontario.ca;Password=[pwd];
OAuth/MFA
I followed instructions: https://reenhanced.com/2020/how-to-connect-with-xrmtoolbox-using-multifactor-authentication

**Expected behavior**
Connect Dataverse without problem.

**Screenshots**
Screenshot with error message is available. Can't find out how to attach it to the current screen. Sorry 

**Desktop (please complete the following information):**
 - XrmToolbox Version: 1.2021.6.51
 - Tool version

**Additional context**
N/A.

**Comment by MscrmTools** [comment]
This connectionstring is not for Oauth/MFA as the authtype is Office365 in your example

Here is an [example](https://docs.microsoft.com/fr-fr/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect#oauth-using-named-account-in-microsoft-365-with-ux-to-prompt-for-authentication)

Or you can use the Oauth/MFA connection method instead of connection string
