### ISSUE TITLE
Add sort order to Tools tab

### ISSUE THREAD

**Issue by georged** [MscrmTools/XrmToolBox#1055]
Some plugin authors start their plugin names with underscores and emojis pushing them to the top of the Tools tab. I prefer sorting by rating/download count but on the Tools tab sorting is not an option. Adding a dropdown to select the property to sort on would be great (plus a checkbox to do a descending?)

Other alternative would be to redesign this tab to behave like a file explorer or at least as a popup Tool Library window - simple grid with custom sorting.

This is somewhat related to #1054

**Comment by MscrmTools** [comment]
@georged, there is already a sort capability for this list, but it's in the Settings dialog
![image](https://user-images.githubusercontent.com/10774317/127522339-a60e501c-e838-42b5-b214-8754e5aa4be8.png)

Of course, I could add the possibility to sort by rating or download.

PS: my own config is always on most used tools, so that I see the tools I use the most first

**Comment by MscrmTools** [comment]
Added sorting by rating
