### ISSUE TITLE
Super Slow & Crashes Often - Takes Hours To Fully Connect - I Hate It - I Can't Work With It

### ISSUE THREAD

**Issue by KristinAMcClinton** [MscrmTools/XrmToolBox#1075]
Super Slow & Crashes Often - Takes Hours To Fully Connect - I Hate It - I Can't Work With It
![image](https://user-images.githubusercontent.com/26823900/136275251-bc9d2569-ca54-40e4-8652-de2058efa5f2.png)

---
- Deployment: Online
- DB Version: 9.2.21085.138
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52

**Comment by MscrmTools** [comment]
XrmToolBox is used by thousand of users everyday, with no complaint.

If I were you (but I'm not, I won't be so rude), I would check my computer and my network. The issue has to be in your side since no one else is complaining about slowness or repetitive crashes.

If you hate it so much, don't use it and do all the work you have to manually

**Comment by SSgumS** [comment]
Hello
In my recent experience with XrmToolBox, Unfortunately it is very slow in fetching data from my on-premise MS CRM (v8.1). It takes about 15 or 20 minutes to fetch data in `Metadata Browser` **or other tools**. In meantime, the official Plugin Registration Tool is working just fine and it seems that the issue is not on my side and it's from XrmToolBox.
My connection string is this: `authtype=AD;url=http://crm/CRM;domain=CRM;username=x;password="x"`.

---
- Deployment: OnPremise
- DB Version: 8.1.1.1005
- Connection Controls Version: 1.2022.5.51
- XrmToolBox Version: 1.2022.5.56
