### ISSUE TITLE
issue about publish

### ISSUE THREAD

**Issue by wrh-byte** [MscrmTools/XrmToolBox#1188]
![image](https://user-images.githubusercontent.com/56340630/205846339-ef68775e-b69b-4963-b5c3-205476344d25.png)
Hi Dear
Greetings!

I did not understand about how to avoid use Early Bound for OptionSet.

**Comment by MscrmTools** [comment]
The problem is with [this file](https://github.com/wrh-byte/OpenSourceWarehouse/blob/main/SolutionComponentSplit/SolutionComponentSplit/Helper-Core/OptionSets.cs).
A plugin cannot contain any Early Bound type because if two plugins are using them, it breaks the whole XrmToolBox when connecting to an environment.
If you need some optionset, create your own class, something not generated with CrmSvcUtil

**Comment by BetimBeja** [comment]
@wrh-byte 
Actually, if you remove `[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]` from the following file: https://github.com/wrh-byte/OpenSourceWarehouse/blob/main/SolutionComponentSplit/SolutionComponentSplit/Helper-Core/OrganizationSdkTypes.cs
I think it should not be a problem for the Early Bound types.

**Comment by daryllabar** [comment]
Yes, that is the actual issue.  You can actually use earlybound as long as you don't use that attribute, and ToEntity<> cast your objects manually.  The Microsoft SDK will search for any assembly with that attribute, and apply the Earlybound types from that assembly automatically.  If the attribute exists more than once for the domain of the App, then it errors.
