### ISSUE TITLE
User Settings Utility

### ISSUE THREAD

**Issue by andz88** [MscrmTools/XrmToolBox#119]
Can I request the User Settings Utility to include the format to be able to be updated in bulk?
At this moment, it is not available and it is a common issue on CRM online instance, where the CRM instance provisioned in US format, but the users are from different region. The system settings only affects the new users, but the existing users will have the US format by default. And it is quite a painful task to instruct every user to change their personal settings one by one.

**Comment by miiiaptyltd** [comment]
I agree completely with this suggestion. This would make things so much easier.
Amazing work on all the Plugins guys.

**Comment by MscrmTools** [comment]
Hi André,

Format is made of lot of attributes and it requires some investigation. But I will try to work on it

**Comment by andz88** [comment]
Thanks Tanguy, I'll try to help investigating this. Will update you for any findings that I could gather.

**Comment by simes1** [comment]
Any more news on this - the user format setting is still very much a problem outside the US with Dynamics 365/CRM Online - especially when organizations are reset.

**Comment by MscrmTools** [comment]
No news, and I don't have time to jnvestigate this myself

**Comment by rajyraman** [comment]
I am already working on getting default dashboard setting. I could look into this as well.

**Comment by simes1** [comment]
Unfortunately I'm not a developer so I can't write this code.  However, from what I understand, there are a myriad of underlying values that are set when one chooses the format for a particular country.  I'm not sure these are defined within the database (and they are bound to be "wrong" anyway for some people/countries).  I believe that this has been the stumbling block for implementing this functionality to date?

Instead of trying to reproduce the functionality present within CRM (i.e. choose a country and it sets all the values) and then use the tool to apply these to multiple users I wonder if it would be better to source these settings from the system format settings or from a sample CRM user's settings?

So the process would be:

1.  Set the format in the System Settings or in a particular user's settings using CRM
2.  Copy the underlying format setting settings from the System Setting or a particular user's settings to the User Settings tool
3.  Apply those format settings to multiple users (along with any other user settings) in the same way the tool does now.

Does that make sense?  Anyone else have any ideas?

--
Simon

**Comment by MscrmTools** [comment]
It does make sense but it would require to test hundreds of possibilities and figure out what number means what setting

**Comment by simes1** [comment]
If that's a problem/too much work don't display the values, or interpret them or allow the user to change anything.  Simply show "format from user x" or "format from system settings" (assuming the second one's possible - i.e. that system settings uses identical settings to user settings).

For a tool the works similarly take a look at the way Windows Regional Settings can be copied from the current user profile to the default and/or system profiles in Windows.

**Comment by Southen** [comment]
There seems to be some confusion about how this works. Changing the overall "localeid" overwrites the more specific format strings such as "dateformatcode" which is probably the biggest use-case.

I have successfully used this snippet to bulk correct the US dates for all users in a client CRM:
```c#
...
foreach (Entity setting in settings.Entities) {
	Entity fix = new Entity("usersettings");
	fix["systemuserid"] = setting.Id;
	fix["localeid"] = 3081;		// English (Australia)
	fix["timezonecode"] = 225;	// (GMT+08:00) Perth
	crmConnection.Update(fix);
}
```
The appropriate values can be found in https://msdn.microsoft.com/en-us/library/cc233982.aspx as hex or can be obtained programmatically with CultureInfo.GetCultures() and [.LCID](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.lcid.aspx)

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MsCrmTools.UserSettingsUtility #10](https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/issues/10) via [**ZenHub**](https://www.zenhub.com/)
