### ISSUE TITLE
version issue in my tool

### ISSUE THREAD

**Issue by Sellouu** [MscrmTools/XrmToolBox#1222]
I developed some enhancements to my published tool,

And update the package and it appeared that it has been updated on the site and Xrmtoolbox,

And when I try to open it using Xrmtoolbox it asks me to update the tool,

And when I approve the update and restart the application it returns with the old version,

I uninstall the tool and re-install it, It also installed with the old version not the new one.

**Comment by MscrmTools** [comment]
Hi @Sellouu, it's just you put your new assembly at the wrong location in the nuget package
![image](https://user-images.githubusercontent.com/10774317/218116060-a0ec0717-d720-47f8-b7c7-eca8e46666b8.png)

**Comment by Sellouu** [comment]
> Hi @Sellouu, it's just you put your new assembly at the wrong location in the nuget package ![image](https://user-images.githubusercontent.com/10774317/218116060-a0ec0717-d720-47f8-b7c7-eca8e46666b8.png)

I updated the package but the issue still exists

![image](https://user-images.githubusercontent.com/109615702/218125078-cc492482-03b0-462f-8d8c-15993d2478e1.png)

**Comment by MscrmTools** [comment]
Of course... You removed the newest assembly from the wrong location but let the old assembly in the correct location...
![image](https://user-images.githubusercontent.com/10774317/218136976-d31e0d47-9f0c-4703-80b1-58831fccb05b.png)

Please be careful what you do so that neither you nor I waste time.
