### ISSUE TITLE
.net 4.8?

### ISSUE THREAD

**Issue by daryllabar** [MscrmTools/XrmToolBox#1237]
According to Matt B, this is safe, but... I'm attempting to reference https://www.nuget.org/packages/Microsoft.PowerPlatform.Dataverse.ModelBuilderLib/ for the EBG.  This is built on the 4.8 framework, but I believe XTB is 4.6.2.  What is preventing us from moving to 4.8?

**Comment by BetimBeja** [comment]
Hey @daryllabar,
I gave a shot at this for `Albanian Early Bound` also... https://github.com/albanian-xrm/Early-Bound/tree/feature/modelbuilder

I am interested in `XrmToolBox` targeting 4.8 too.

Beware! I raised this issue that was "ignored" https://github.com/microsoft/powerplatform-vscode/issues/373

I haven't had time to update my tool because there is a lot of "dead code" in there with the new Model Builder.

**Comment by MscrmTools** [comment]
I really don't know what would be the impact of moving to 4.8

**Comment by daryllabar** [comment]
Sounds like we need a public beta ;)

**Comment by daryllabar** [comment]
For what it's worth (Lucit is Matt B):
![image](https://user-images.githubusercontent.com/9728423/222755811-6207e5aa-204c-445c-ab70-d4b99bbce039.png)

**Comment by MscrmTools** [comment]
ok, as soon as I have finished validating the beta connection controls, I will work on the next version of XTB and I will be able to move to framework 4.8

**Comment by daryllabar** [comment]
@BetimBeja I'm unable to get the WriteSettingsTemplate flag to work.  How do you know the format of the file?

**Comment by MscrmTools** [comment]
Hi guys,

Here is your Framework .Net 4.8 version. 

It is shipped with latest connection controls and the brand new Settings form. Please test them also :)

![image](https://user-images.githubusercontent.com/10774317/223137836-df63608e-c314-42ae-a338-d0bd09e22ab0.png)


![image](https://user-images.githubusercontent.com/10774317/223137243-248e13b1-b32a-482e-b53c-a0c5f5bf69d9.png)


[XrmToolbox.zip](https://github.com/MscrmTools/XrmToolBox/files/10899147/XrmToolbox.zip)
