### ISSUE TITLE
Cannot open SQL 4 CDS

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1276]
It's been a while since I last opened it, and I got the update to new version (7.4.0.0) so I got the update, no problems there.
But when trying to open SQL 4 CDS, I always get this:

```
An error occured when trying to display this tool: Length cannot be less than zero.

Parameter name: length
```
![image](https://github.com/MscrmTools/XrmToolBox/assets/2572253/21546287-8fe4-4c4d-b653-dcf77c5e5fbd)

Not sure if this error is in XTB or in the tool, so I also ping @MarkMpn.

---
- Deployment: Online
- DB Version: 9.2.23075.194
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.6.65

**Comment by MarkMpn** [comment]
In the latest version I stopped using ILMerge to combine all the assemblies, and load the dependencies at runtime using the AssemblyResolve event.

Because all plugins are loaded when XTB starts, they can all add their own handlers to this event. I believe the error you’re seeing will be being thrown by one of them - you’ll need to attach a debugger and look at the call stack of the exception to see which.

There’s probably a change I could make to avoid this particular error, but it’s likely there will be other related problems depending on which tools you have installed. I’m planning to see if I can isolate SQL 4 CDS into a separate app domain to avoid anything similar in the future.

In the meantime if you’re experiencing this problem with 7.4 you should be able to downgrade to 7.3 to avoid it for now.

**Comment by rappen** [comment]
Works fine now!

---
- Deployment: Online
- DB Version: 9.2.23081.184
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.9.66
- Tool Version: 7.5.0.0
---

Closing this issue.
