### ISSUE TITLE
Execute through Command Line?

### ISSUE THREAD

**Issue by Betina-Dalope** [MscrmTools/XrmToolBox#136]
I'm using the Import/Export NN relationships tool.  Is there a way to connect to the CRM and use this tool all through the command line or command prompt?  I'm trying to add an nn relationship import to a nightly, scheduled process.

**Comment by shytikov** [comment]
Hi @Betina-Dalope,

There is a way to start particular plugin and connect to particular database using command line parameters. You can take a look on #93.

I don't know will it satisfy your need or not. If not, could you please describe in more detail your scenario, maybe I can come up with some kind of solution.

**Comment by Betina-Dalope** [comment]
Yes, thank you.  I took a look at #93, but it doesn't completely solve my problem.

I'm using Jitterbit, a data loading server, to import and update CRM entities from a corresponding database tables.  But I also want to import the nn relationships between these new records, but Jitterbit does not allow that.  I was hoping to use both Jitterbit and XrmToolBox, but Import/Export NN Relationships needs to be completely run by command line in order for it to work.  That way, I can add the nn relationship import to a scheduled process managed by Jitterbit, instead of manually executing the process every night.  I really just need to be able to choose which entity I'm importing to, point to the semi-colon delimited file, and execute the import process.

**Comment by shytikov** [comment]
Can you take a look on http://www.autohotkey.com/ It's a script language / runtime to automate some routine actions, maybe by adding it to the picture it will make a puzzle complete? In this case maybe it would be able to select entity you're importing to, select file and start the process.

**Comment by shytikov** [comment]
I also have another idea for you.

The main problem in `XTB` implementation of what you're asking for is the specific parameters plugin requires to start execution: entity, file with values... I cannot build generic way to start all the types of plugins, since each one of them actually requires different approach.

But!

If you take a look on #96, you will see that there is a mechanism of sending messages between plugins. So...

1. You can create simple plugin the only action performed is to send hardcoded message to `Import/Export NN relationships tool` with correct parameters.
2. Plugin will be triggered from command line and send the message.
3. `Import/Export NN relationships tool` will do the work as soon as message arrives;

A bit tricky, but it should make a job done...

In any case, let's wait what will @MscrmTools say. Your business case is very interesting, and I pretty sure `XTB` can cover it. The main question how to do it right.

**Comment by MscrmTools** [comment]
This feature request will need to add automation to each and every plugin when receiving messages. I think it will require lot of work.
Not especially if we consider only the NN import/export plugin but if we include this kind of logic, then it should be done for most of the plugins

I clearly don't have time these days to think about it but maybe later...

**Comment by shytikov** [comment]
@Betina-Dalope there is one way if you a bit familiar with C#. Since source code is freely available you're able to add needed changes to `Import/Export NN relationships tool` yourself, recompile it and put it to `XTB` plugins folder.

It should really simple change, just hardcode some values, and make plugin start execution and soon as connection is established. Or you can read values from configuration file, it will be more flexible.

If you can consider that approach, you will also need to rename plugin, both it's title and filename. This will ensure that original plugin will still be available alongside with the modified one if you need it someday.

**Comment by Betina-Dalope** [comment]
thank you very much for your help
