### ISSUE TITLE
Focus plugin when selecting tab

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#153]
For my specific needs in FXB I have implemented OnLeave and OnEnter event handlers.
Changing to another tab in XTB naturally fires the OnLeave, but when going back to the FXB tab there is no OnEnter fired until I actually click somewhere within the FXB window.

It would be great if selecting a tab immediately would do something like:
``CurrentTab.GetControl().Focus();``

**Comment by MscrmTools** [comment]
Focus does not fire OnEnter in my tests

**Comment by MscrmTools** [comment]
@rappen, this does not seem to work

Have you another idea?

**Comment by shytikov** [comment]
@rappen @MscrmTools Maybe we can find another even that will properly fit the case? for example `OnVisibleChanged`?

It's not ideal, since we actually not hiding plugin when we navigating from it (so `OnLeave` event is still needed).

And during creating of plugin `OnVisibleChanged` fires several times (probably internally we're doing some manipulations with plugin control).

So recipe will be after initiation of plugin (this will filter initial `OnVisibleChanged` calls) subscribe to `OnVisibleChanged` and `OnLeave` events. 

If this will be not enough for solving the issue? Or should we do it properly (i.e. create special event like `PluginGotFocus`, `PluginLostFocus` and trigger them explicitly)?

**Comment by MscrmTools** [comment]
Ok, it actually works when focusing on the control in the tab!

**Comment by rappen** [comment]
Yohoo! :+1:

**Comment by MscrmTools** [comment]
available in pre release (when build is done)
