### ISSUE TITLE
Update connection dialog does not show organization name

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#16]
When editing connection, dialog does not contain information about organization, while it is present in configuration file and used for connecting to the server.

![No organization](http://i.imgur.com/eHcZS3v.png)

**Comment by MscrmTools** [comment]
I think I made this by design... As you will update the connection, forcing to retrieve organizations ensure the updated configuration is valid

**Comment by shytikov** [comment]
But if we name connection not same as organization? The update connection window will lack organization name completly

**Comment by daryllabar** [comment]
I think it would be helpful to leave the name there, and when they click OK, validate that the server still has that org, performing the same Organization Lookup that happens when you click Get Orgs.  If the new server info/credentials are missing that org name, then throw up an alert box saying so, and use the results of the Discrovery Service Request to populate the Org Selection Dialog that is normally used.
