### ISSUE TITLE
Lazy loading not working

### ISSUE THREAD

**Issue by paddyfink** [MscrmTools/XrmToolBox#256]
According to ms :By using the CrmOrganizationServiceContext, or the generated XrmServiceContext, you have the most concise code for accessing relationships. This context allows automatic lazy loading of related entities by tracking the context reference internally and calling LoadProperty implicitly, as shown here.

using (var service = new OrganizationService(connection))
using (var context = new CrmOrganizationServiceContext(service))
{
// this context manages the context reference internally
var contact = context.CreateQuery<Contact>().First(c => c.FirstName == "Bob");
var currency = contact.transactioncurrency_contact;
Console.WriteLine(currency.CurrencyName);
}

But it doesn't work. Related entities are always null.

In order to work, the CrmSvcUtil.exe  has to be executed with :
/codeCustomization:"Microsoft.Xrm.Client.CodeGeneration.CodeCustomization,Microsoft.Xrm.Client.CodeGeneration". 

But your tool use :  
/codecustomization:"DLaB.CmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" 

is it related?

**Comment by daryllabar** [comment]
I'm assuming this is a specific question for the EarlyBoundGenerator?

By default, the code generator will not inherit from Xrm.Client.Entity since this requires an additional dll dependency that isn't on the server by default, and will require plugins to be merged.

If you want your service context to inherit from CrmOrganizationServiceContext, and conversely, Entities from Xrm.Client.Entity, check the "Use Xrm Client" on the Entities tab.

This results in a dependence on Microsoft.Xrm.Client.dll that must be accounted for during plugins and workflows since it isn't included with CRM by default:
http://develop1.net/public/post/MicrosoftXrmClient-Part-1.aspx .

**Comment by paddyfink** [comment]
yes it's for EarlyBoundGenerator.

I checked the "Use Xrm client". My XrmServiceContext derive from CrmOrganizationServiceContext. Everything works fine, except the lazy loading. It's not a big deal since I can use join query. I just wanted to compare the performance between the join and the lazyloading

**Comment by daryllabar** [comment]
I have never used the lazy loading.  If you get it working let me know how it works.

**Comment by MscrmTools** [comment]
Please open an issue in @daryllabar repository if needed. I close this one
