### ISSUE TITLE
It is possible to load two copies of the same plugin by changing `dll` name

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#26]
`XrmToolBox` will load same plugin twice if its `dll` will be copied to the `XTB` folder with different name.

It is potential flaw, since from time to time plugins may change names of their dlls. For example in case if plugin scope was increased, and it become something more general, than it was before. Or, for example if `XTB` will require all plugins to comply some naming conversion in the future. In this case, `XTB` will find both old and new version of plugins in the folder.

I think application should rely on plugin unique identifier and its version. Among two plugins with same `id` but different versions, greater version should be taken.

In case of same ids, same versions, but different names, user should explicitly make a decision what behavior is desirable:

* Remove one of plugins and load other;
* Load both;

**Comment by MscrmTools** [comment]
Interesting feedback @shytikov 

I think I should redesign the way plugins are loaded since I'm not using any AppDomain to load plugins. Then I could handle this behavior

**Comment by MscrmTools** [comment]
I'm testing how to use MEF to create a real plugin enabled application. When my tests are complete, I think I will start updating XrmToolBox to use MEF.
I'm not sure I will have time to do it for May release so maybe for June release

**Comment by shytikov** [comment]
Would be interesting to take a look at implementation, I'm completely unfamiliar with MEF (`Managed Extensibility Framework`, right?)...

**Comment by MscrmTools** [comment]
There is not a lot of tutorials on MEF but I found this one which does exactly what I'm trying to achieve : using UserControls as plugins

This tutorial shows how developers dealt with "plugins" before MEF (what I am basically doing today) and how to implement MEF.

MEF has to be used if we want to be able to update plugins right in XrmToolBox since using MEF does not lock assemblies since they are shadow copied elsewhere. I jus thave to validate communication between plugins and main application (requesting a connection, updating connection, etc.)

Here is the link: www.abhisheksur.com/2011/08/steps-to-write-plugin-based-application.html

**Comment by shytikov** [comment]
:+1:

**Comment by MscrmTools** [comment]
MEF can definitively fix this kind of problem. See #131

**Comment by MscrmTools** [comment]
Fixed in DEV branch using MEF.
