### ISSUE TITLE
connection.WebApplicationUrl is null

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#27]
I tried to use the newly introduced `connection.WebApplicationUrl`but it returned null.
I was connected ok and using `ServerName` and `Organization` to compose the url manually worked fine.

**Comment by MscrmTools** [comment]
This should works only for newly created connection since this value is returned by discovery servicve

**Comment by rappen** [comment]
You mean it is stored in config file, and if connection was created in earlier version of XTB?
If so, it would be nice to update existing connections when they are used, so that we can trust this property of the connectiondetail :)

**Comment by MscrmTools** [comment]
As mentionned, the problem is this information is available only through DiscoveryService. That would mean each time the user connect, I should query DiscoveryService again to get the latest information. 
I can do this, but it's an extra query so it will take more time...
And this information shouldn't change unless a real IT change, which leads to recreate the connection anyway

**Comment by rappen** [comment]
I didn't mean to always do it, just IF the WebApplicationUrl has not been stored in the file. It would be a one time action to be backwards compatible with the config file :)

**Comment by MscrmTools** [comment]
Sure! will try to implement that
