### ISSUE TITLE
Manage NN relationiships

### ISSUE THREAD

**Issue by nevinAnderson** [MscrmTools/XrmToolBox#287]
Hi Tanguy, thanks for this tool!! When the file is not correct I see errors. Once I have the import file set up correctly, then nothing happens when I run Import. Any idea how I can get this working right?

**Comment by MscrmTools** [comment]
Can you show first lines of your file just to be sure?
Also, what version do you use?

**Comment by nevinAnderson** [comment]
Hello MscrmTools, thank you for your reply!  The file consists of the following three lines:
{62e2af55-6d92-e511-80e3-3863bb36edb0};GARAGE
{62e2af55-6d92-e511-80e3-3863bb36edb0};A/C
{62e2af55-6d92-e511-80e3-3863bb36edb0};BUILDINGS

**Comment by MscrmTools** [comment]
Hi,
I know I should probably put some check to avoid this situation but the separator is not the right one. 
I used to use semicolon as separator and replaced it with comma since it seems it is the default delimiter for CSV files (except in France, where it is semicolon)

So please try to replace semicolon with comma and you should be good!

**Comment by nevinAnderson** [comment]
Yes, thank you!  Changing semicolon to comma was the trick!
