### ISSUE TITLE
A Sample Tool WhoAmI not returning result

### ISSUE THREAD

**Issue by davidmcd** [MscrmTools/XrmToolBox#324]
I'm trying to learn to write my first plug-in.  I was doing a simple WhoAmI just like the plug-in "A Sample Tool".  I noticed that A Sample Tool never returns the result of its WhoAmI (that's a bug).  

Is there documentation for WorkAsync() so that I can figure out why it doesn't work?  Or would someone please fix/update the "A Sample Tool"?  Any help is appreciated.  

Note that the code that i'm talking about that isn't working is in the wiki under "Final Complete Class" here:  https://github.com/MscrmTools/XrmToolBox/wiki/Develop-your-own-custom-plugin-for-XrmToolBox

**Comment by daryllabar** [comment]
The work async is a little confusing because it is so flexible.  Basically, you give it the work to do as an action (Method Pointer).  This then runs on a separate thread. You also can define callbacks for what to do on completion, as well as what to do for progress changes, although these are all optional.  These optional parameter are populated as properties on the WorkAsyncInfo object.

What exactly seems to be your current issue?

**Comment by daryllabar** [comment]
@davidmcd did you figure your issue out?

**Comment by MscrmTools** [comment]
The sample code shows how to use the cancellation feature but never shows the result, you are right... I will simplify the sample code in the wiki

**Comment by MscrmTools** [comment]
done
