### ISSUE TITLE
FetchXml tester uses Execute message rather than RetrieveMultiple

### ISSUE THREAD

**Issue by surrealjam** [MscrmTools/XrmToolBox#326]
The FetchXml tester application uses the Execute message to retrieve records from CRM. This is a rather outdated way to retrieve records given we have a specific RetreiveMultiple message.

Is there any reason why this is used? We (and I imagine quite a few others) have specific logic applied to the RetrieveMultiple message where it is easier to manipulate both input and output parameters for the plugin execution context. Using the Execute message bypasses these.
```C#
var fetchXml = "<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'><entity name='contact'><attribute name='fullname' /><attribute name='contactid' /><order attribute='fullname' descending='false' /></entity></fetch>";
var results = service.RetrieveMultiple(new FetchExpression(fetchXml));
```

**Comment by rappen** [comment]
I would recommend using FetchXML Builder instead, which offers different options for retrieval and many other things.
http://fxb.xrmtoolbox.com

**Comment by surrealjam** [comment]
Thanks - I was thinking more of an end user having access to XrmToolbox and therefore bypassing the implemented business rules. I have incidentally started to use FetchXML Builder as well and that indeed seems to have a lot more functionality. Is there a plan to replace the FetchXML tester with FetchXML Builder longer term?

**Comment by shytikov** [comment]
I think it would be very nice to consider adding third-party plugins to main `XTB` package.

There are many great tools developed, but their existence is not very clear for user, since we don't have mechanism to search for all plugins available.

@MscrmTools do you think it could be feasible to add some tools developed by community as part of standard distribution? I'm specially implying on `Early Bound Generator` and `FetchXML Builder`, if @daryllabar or @rappen would not mind?

This thought came after I installed and set up `XTB` for several developers in the raw. First things you do after downloading core, you download these two plugins... So maybe?.. In terms of stability and quality they both look very good.

I believe it it would be done technically as git submodules, and legally clearly stated that all credits and support requests should be forwarded to respective users.

**Comment by daryllabar** [comment]
@shytikov can you copy your comment to a new issue?  I've talked a little bit with @MscrmTools about how to best do that, and deserves its own thread.

**Comment by shytikov** [comment]
Sure!

**Comment by MscrmTools** [comment]
Regarding FetchXml tester, the tool comes from old ages of CRM 4 where it was not possible to RetrieveMultiple with Fetch
I can update it anyway

**Comment by rappen** [comment]
@surrealjam "Replacing" in this case would mean that MscrmTools simply drops FetchxmlTester from the XrmToolBox package.
FetchXML Builder is not developed by the XrmToolBox developer, but by me (and the occasional open source community developer). So this is a third party plugin to XTB and delivered as such.
Possible bundling of third party tools in the future can now apparently be followed in #327 :)

**Comment by surrealjam** [comment]
@rappen Yeah, to be honest, I thought that several of the tools within the standard XrmToolBox were "third party" plugins that were just bundled with the overall package. That is just my misunderstanding. 

I agree item #327 would be great to get up and running - it's a shame that some great tools are probably going unnoticed by CRM developers. Indeed, I wrote my own FetchXml to QueryExpression application before knowing that XTB existed!

**Comment by MscrmTools** [comment]
Just looked at the code... if using RetrieveMultiple, then I cannot provide XML result...
So I'm not going to update the code
