### ISSUE TITLE
Unique name for organization error

### ISSUE THREAD

**Issue by DebSil** [MscrmTools/XrmToolBox#361]
I'm attempting to set up a new connection to our online instance which uses ADFS Cloud authentication.  Each time I enter my credentials --- whether I tell it to use my "current" credentials or retype them -- it returns the error "If the unique name for your organization is different from the name used in the url you provided, please replace the organization name in the url with the organization unique name."

I'm using the URL copied and pasted from my URL when logged into the site; i.e.,
https://chesterfieldcoreint.crm9.dynamics.com

Are there any issues with authentication through the Office 365 portal via ADFS?

**Comment by mscottsewell** [comment]
@DebSil - I experienced the same challenge as you are - but fortunately there's a fix. :)
You will need to open CRM and get the 'unique' name for the organization it's found on the 'Developer Resources' page in the customization area of your CRM.- The process is described and illustrated here - https://github.com/MscrmTools/XrmToolBox/issues/299#issuecomment-169771747
The value (under the red squiggle in the screenshot) is unique to your organization - use that string instead of 'chesterfieldcoreint' in the URL for the toolbox - it'll look funny but work fine.

**Comment by MscrmTools** [comment]
A workaround is on its way for the next release that will explore all organizations you have access to to match url org name

**Comment by MscrmTools** [comment]
I close this issue since a fix is coming for next release.
