### ISSUE TITLE
Occasional Audit Center Error when publishing changes - 

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#435]
Occasionally I get an error when applying changes - I assume there's a field that is not audit-enabled in my set, but I can't always see which one it is.

Here's the message I see - 
![2016-06-07_10-36-16](https://cloud.githubusercontent.com/assets/6276300/15862082/81a7b9d0-2c9c-11e6-8c2f-69a2711c7ae6.png)

(Additionally there are some internal-use fields such as 'versionnumber' and 'traversedpath' that show up occasionally and should always be excluded.)

**Comment by mscottsewell** [comment]
BTW - I'm not blocked by this - just something to resolve next time you get into this code.

**Comment by MscrmTools** [comment]
Thank you for the feedback Scott! always appreciated!

**Comment by MscrmTools** [comment]
I just analyze a bit more in depth and the problem here is that CanModifyAttributeAuditSettings is a SQL column not exposed in CRM SDK so I cannot filter out attributes based on this value...

As for traversedpath, it is defined as customizable and should allow to change its audit flag
For 'versionnumber', yes, it should be excluded as it is not customizable

**Comment by MscrmTools** [comment]
Issue moved to [MscrmTools/MscrmTools.AuditCenter #1](https://github.com/MscrmTools/MscrmTools.AuditCenter/issues/1) via [**ZenHub**](https://www.zenhub.com/)
