### ISSUE TITLE
Conflict between DLaB Attribute Manager and Ribbon Workbench

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/XrmToolBox#445]
There's some type of problem with isolation between plugins - I'm not sure if it's related to the Ribbon Workbench, the DLaB plugin - or just something in the overall structure - 

If the DLab Attribute manger is installed (not even running) and you launch the Ribbon Workbench beta, 
you get script errors - 
![ribbon workbench error](https://cloud.githubusercontent.com/assets/6276300/16357043/5b0737da-3ab9-11e6-8bdf-1d65b42c4d2a.png)

Deleting these files allows the ribbon workbench to launch.
![image](https://cloud.githubusercontent.com/assets/6276300/16357048/83c70f60-3ab9-11e6-98ff-7079b9face60.png)

**Comment by daryllabar** [comment]
I believe this is due to plugins not being able to specify the version of EarlyBound Assemblies to use.  The SDK will actively seek out the EarlyBound Assembly dll, and attempt to use that.  I believe the toolbox will need a way to specify a version of EarlyBound Assemblies to use.  @MscrmTools has already talked about adding his own Early Bound Assemblies, in an effort to force all others to use that version, rather than every single plugin having their own.  This would be one way to alleviate the situation, but not entirely stable...

**Comment by MscrmTools** [comment]
Scott Durow advice is to force developers to use late bound entities... 

Are early bound entities mandatory to use for you Daryl?

**Comment by daryllabar** [comment]
All my stuff is using EarlyBound, so I'd have to rewrite all of it.  Does each plugin get its own IOrganizationService?  Or are they shared?

**Comment by MscrmTools** [comment]
Iorganization is cloned for each plugin opened

**Comment by daryllabar** [comment]
Is there a replacement for the ProxyTypesAssembly Property in CrmConnection class?  I'm assuming there is some way to define for each IOrganizationService, what the Assembly Proxy should be.

**Comment by daryllabar** [comment]
Actually, see: https://github.com/MscrmTools/XrmToolBox/issues/353

**Comment by MscrmTools** [comment]
As mentioned by @daryllabar , there is already an issue for this problem and RibbonWorkbench has been updated to resolve this conflict.
I close the issue
