### ISSUE TITLE
XrmToolBox.exe detected as Win32/Trojan.97a by 360 Total Security Antivirus (360 Cloud Scan Engine)

### ISSUE THREAD

**Issue by MFerreiraUy** [MscrmTools/XrmToolBox#458]
The executable is detected as troyan when I try to run the exe file. The version is the last one (June release). Previous release from May doesn´t have this problem.

 
![image](https://cloud.githubusercontent.com/assets/20862962/17443782/ef7166e2-5b12-11e6-905f-c3c999f90911.png)

**Comment by shytikov** [comment]
That's really strange. Sometimes these anti-viruses false-detect stuff... Definitely looks scary, but you can download source code from here, and compile it yourself using free Visual Studio Community Edition. In this case you could be sure that executable is not infected (because you just compiled it yourself a moment ago).

**Comment by MFerreiraUy** [comment]
Hi, thank you for your response!. I just tried this site: https://www.virustotal.com/ were you can upload a file and they run it with different Antivirus engines (they use 54 engines to test the file!!). Between the 54 engines (like AVG, Avast, Avira, ESET, Kaspersky,  McAfee, etc) only the 360 engine is marking it as a Trojan. So, as you suggested, this seems to be a false positive.

![image](https://cloud.githubusercontent.com/assets/20862962/17447893/8e8b4946-5b27-11e6-8b33-cbd7c32d91e5.png)

(the image continues with other Engines, all of them Ok except the 360 engine)

**Comment by MscrmTools** [comment]
Closing the issue then
