### ISSUE TITLE
Capability for plugins to declare minimum crm version

### ISSUE THREAD

**Issue by rajyraman** [MscrmTools/XrmToolBox#494]
I think it would be good if plugins can declare minimum crm version they need to work (a new class attribute), so that XrmToolBox can hide/not start plugins incompatible with crm version while initiating/switching version. For e.g Plugin Trace  Viewer is incompatible with CRM2015, so it displays "The entity with a name = 'plugintracelog' was not found in the MetadataCache." error when you try to connect a CRM2015 instance.

If this is taken care by the base class, plugin devs can be confident that any plugin exceptions/weird behaviors are not due to the version of crm.

**Comment by rappen** [comment]
👍

**Comment by MscrmTools** [comment]
That is a nice suggestion! 

I can add it as an interface to avoid including a breaking change.

In the mean time, developer can read the ConnectionDetail object to check the current version of organization and warn the user appropriately

**Comment by daryllabar** [comment]
I'm not sure I'm in favor of adding this because you still have the issue with future versions of CRM being incompatible as well.  Each plugin should be checking for the version of CRM in the ConnectionDetail Object and handling it appropriately.

Consider these two issues:

1. What happens if I change from CRM 2016 to CRM 2015?  Should invalid plugins disappear?
2. What if I have a favorite plugin and it isn't showing in the list because I'm not connected to a compatible version.  Where did it go? Did I install it?  etc...
3. Bonus: This doesn't do anything for handling the user opening a plugin before connecting...


Check the Connection Detail object and Fix your plugin @rajyraman  ;)

**Comment by rajyraman** [comment]
Functionally, I was thinking more along the package.json in node. I like how you can specify your dependencies with minimum version required. For things that may not work in CRM OnPremise, as a feature/entity/sdk message that the tool relies on is Online only, plugin developers can still release the tool and specify that you need at least 8.1.0 and/or be in CRMOnline to use the tool. It won't be hard to do this at the tool level, but I think it would be nice if base can handle it.

May be there can be a check just before XrmToolBox loads the tool, to see if the tool is incompatible with the current CRM connection and display a warning message, leaving it up to user the choice to proceed or close? 

How are you handling fetchxml schema differences across CRM versions @rappen? Do you send it to CRM and display the error message to the user after the fetch executes?

**Comment by daryllabar** [comment]
> May be there can be a check just before XrmToolBox loads the tool, to see if the tool is incompatible with the current CRM connection and display a warning message, leaving it up to user the choice to proceed or close?

Just remember, that users can normally change their connection at will (although the Ribbon Workbench has disabled that feature)

**Comment by MscrmTools** [comment]
I agree with Daryl, it could be not so obvious...
As developer can already check for version using ConnectionDetail object, I think we are good here

**Comment by MscrmTools** [comment]
May I close this issue swithout frustrating anyone?

**Comment by rappen** [comment]
Consider me unfrustrated!

**Comment by rajyraman** [comment]
yup. no issues.
