### ISSUE TITLE
Delete saved user personal views?

### ISSUE THREAD

**Issue by chrisdavies83** [MscrmTools/XrmToolBox#606]
Hi, is there a way to delete saved personal views on behalf of users in CRM?

**Comment by MscrmTools** [comment]
Yes, that could be achieved through code but there is no plugin in XrmToolBox that does it

**Comment by tyler-hogsett-microsoft** [comment]
@MscrmTools, I know this is an old thread, but I was working with a customer who was having problems with Saved Views owned by disabled users and needing to delete or correct them. In my testing, I was not able to find any programmatic way to do so without unsupported SQL shenanigans. System Administrators cannot see other users' saved views, even when making SDK calls impersonating those users. Can you please provide a general outline on how this might be done?

**Comment by bwmodular** [comment]
@tyler-hogsett-microsoft I don't think there is a way to amend user views without impersonating the user who owns the view, and you cannot impersonate a user unless they are active and have at least one security role.

If you really need to do this, you're going to have to re-enable the user, after which you could assign the view to an active user and then re-disable the original user.

@chrisdavies83 I've blogged about programatically removing attributes from user views [here](http://blogs.it.ox.ac.uk/benwalker/2018/02/08/programmatically-removing-attributes-from-user-views-in-dynamics-crm/) - the process for deleting saved views would be similar but less complex - you just need to impersonate the user who owns the view (by changing the callerId of the organisation service to that of the user who owns the view) and you can then delete the saved view like any other entity.

**Comment by tyler-hogsett-microsoft** [comment]
@bwmodular Are you sure that impersonating a user will allow you to delete their views? I have tested this in 8.2 (on-premises) and in 9.0.2 (online), and even through impersonated requests (unless I'm doing something wrong), when you go to retrieve personal views via SDK calls, you only receive the views of the initiating user. This is not documented (to my knowledge), but there are certain SDK calls that seem to ignored the CallerId property of the OrganizationServiceProxy.

**A fun note:** WhoAmIRequests also do not retrieve the guid of the CallerId, but instead of the initiating user, which is great when you want to do a sanity test to make sure your calls are indeed getting impersonated. You need to do something somewhat invasive, like create or update a record.

**Comment by MscrmTools** [comment]
AFAIK, you CAN retrieve impersonated user views unless something changed in the SDK

**Comment by tyler-hogsett-microsoft** [comment]
Thanks! Not sure what I was doing wrong before, but somehow I seem to be able to retrieve users' views using impersonation requests now.
