### ISSUE TITLE
Unable to initialize the native configuration support external to the web worker process

### ISSUE THREAD

**Issue by Panoone** [MscrmTools/XrmToolBox#778]
Before creating an issue, please ensure you are in the appropriate repository:
- for connectivity issue, please submit an issue in [MscrmTools.Xrm.Connection repository](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues)
- for plugins issue, we only accept issue for plugins from MscrmTools that don't have their own repository (which are, as of today: MsCrmTools.FetchXmlTester, MsCrmTools.MetadataDocumentGenerator, MsCrmTools.SolutionImport and MsCrmTools.SynchronousEventOrderEditor). Any other plugin issue should be created on their respective repository

**Comment by Panoone** [comment]
I'm receiving this error immediately after I connect. It doesn't appear to affect app functionality.

 Unable to initialize the native configuration support external to the web worker process (HRESULT=0x80040154).  nativerd.dll must be in %windir%\system32\inetsrv.

**Comment by Panoone** [comment]
Yes I tend to agree. Seems to be a .NET Framework issue on my PC.

**Comment by paoloursino** [comment]
The issue may be closed but I have the same identical problem and wasting days to understand what to do. Any chance to know if/how this was fixed?

**Comment by lijnloos** [comment]
> The issue may be closed but I have the same identical problem and wasting days to understand what to do. Any chance to know if/how this was fixed?

I have the same issue/question. I'm missing the dll but cannot pinpoint which update did this... I undid 2 Microsoft updates but no results. Anyone know which update removes this dll?

**Comment by rodmilne** [comment]
I ran into this problem right after updating my windows 10 to mos recent version yesterday.  I found that you have to turn on http activation under the windows features. 
![windowsfeature_http](https://user-images.githubusercontent.com/3642310/57893238-053caa00-77f7-11e9-9763-56de0d54b362.png)
t

**Comment by MscrmTools** [comment]
Thank you for the feedback!

**Comment by piyushpaliwal** [comment]
> 
> 
> I ran into this problem right after updating my windows 10 to most recent version yesterday. I found that you have to turn on http activation under the windows features.
> ![windowsfeature_http](https://user-images.githubusercontent.com/3642310/57893238-053caa00-77f7-11e9-9763-56de0d54b362.png)
> t

This indeed solved the problem, but I was wondering how did you figured out that this particular setting will resolve the issue?

**Comment by rodmilne** [comment]
My supreme googling skills :) but I had to get it resolved as I was working on a project and suddenly XrmToolbox wasn't working.  I cross referenced the error and started to try what was logical.  Wasn't sure why the issue was pointing to a dll in inetsrv, but when an article came up about the HTTP activation, it seems logical that WFC would be used to communicate with CRM.  Since my computer had done a recent windows update, i could only figure, what I had in place in supporting dlls must have been changed.

**Comment by mscottsewell** [comment]
Thanks, this resolved this annoyance for me as well. (after Windows 10 refresh.)

**Comment by ehandani** [comment]
I ran into this error on logging in USD which was installed after win 10 updates. This solved the issue. Thanks!

**Comment by MattB-msft** [comment]
As a Note to others who find this thread,   This issue was caused by a underlying issue in .NET 4.8 which is installed with the w10 refresh.  We ( Microsoft ) released an updated connector that remove the dependency on the 'thing' that was causing this issue.  [this](https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/9.0.2.25) Nuget and forward have the update for custom apps.
