### ISSUE TITLE
Created a new Windows profile and can't restart XRM Toolbox

### ISSUE THREAD

**Issue by popujol** [MscrmTools/XrmToolBox#788]
Hello,
First of al thank you for  your tool ! I haven't found simlar errors than mine so I would be hyppa if you can tell what you think about it.
When I start xrmtoolbox, it looks the application is looking for the connection file at the wrong place.
I had to reset a new windows profile and the error message doesn't seem to be able to open it, in fact it is pointing the old user profile (my guess)

 See the picture attached,
![2018-07-30 20_04_30-error](https://user-images.githubusercontent.com/40460576/43414838-4106bc80-9434-11e8-94b4-7ca705e955b6.png)

Many thanks for you help.

Pierre-Olivier

**Comment by MscrmTools** [comment]
You just need to identify the file that stores all other connection files. This file should be located in XrmToolBox storage folder, then Settings folder

**Comment by shytikov** [comment]
I believe this happens because `MscrmTools.ConnectionsList.xml` file in your `XTB` folder contains link to the connections file as full path. So when you moved or renamed your profile, old location became inaccessible.

Definitely this situation should be handled gracefully, without ugly exceptions, but meanwhile you will be able to workaround that by updating path in `MscrmTools.ConnectionsList.xml`.

**Comment by shytikov** [comment]
Check contents of the file: `c:\Users\[your_new_username]\AppData\Roaming\MscrmTools\XrmToolBox\Connections\MscrmTools.ConnectionsList.xml `. Most likely it contains link to the connections file that is located under your old username's folder.

Just update the path, it should load everything properly. 

But definitely you're right `XTB` shouldn't crash because of that, if location is not available it should be discarded silently.

**Comment by shytikov** [comment]
I've added simple fix for that: it will not search for new file location, but it will not explode either.

**Comment by popujol** [comment]
Thank you very much for your help.
I updated Connectionslist.default to the correct patch but the same error is appearing showing the old path.
Is there a cache to clean somehow?
Thank you!

Pierre-Olivier

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by shytikov** [comment]
Not sure that cache exists... 

Do you have several connections files? Just checking :) Because according to the code `XTB` will attempt to open the **last one**. And it will determine that by sorting them according to a value in `<LastUsed>` attribute.

So if you have several of them it might be that you have updated not the last one... Can you check that theory?

**Comment by popujol** [comment]
Hi all,

I could finally repair the connection.
I created the former path to put my connection folder, then I could restart XRMToolbox and reset the connection as I want them on my current windows profile.

Thanks a lot for your support whitout I could not find the solution !

Have a good day.

Pierre-Olivier
pop_pujol@hotmail.com
________________________________
De : Alexey Shytikov <notifications@github.com>
Envoyé : mardi 31 juillet 2018 09:06
À : MscrmTools/XrmToolBox
Cc : popujol; Author
Objet : Re: [MscrmTools/XrmToolBox] Created a new Windows profile and can't restart XRM Toolbox (#788)


Not sure that cache exists...

Do you have several connections files? Just checking :) Because according to the code XTB will attempt to open the last one. And it will determine that by sorting them according to a value in <LastUsed> attribute.

So if you have several of them it might be that you have updated not the last one... Can you check that theory?

**Comment by shytikov** [comment]
@popujol glad it worked!

@MscrmTools should we close this issue?

**Comment by MscrmTools** [comment]
Yes indeed
