### ISSUE TITLE
I cant open XrmToolBox

### ISSUE THREAD

**Issue by Mykel96** [MscrmTools/XrmToolBox#816]
So if I want to open XrmToolBox as usual an this error message pops up:

**An unexpected error occured: System.ArgumentException:
Invalid DockState: Content can not be showed as "Unknown" or "Hidden".
bei WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(
DockPanel dockpanel, DockState dockState)
bei XrmToolBox.New.NewForm..ctor(String args)

One reason can be that at least one file is locked by Windows. Please unblock each locked files or unlock XrmToolBox.zip before extracting its content**

I deleted XRMToolBox and than downloadet the newest version. I unblocked the whole zip folder and than extractet its content. But still this error message keeps poping up when I try to open XRMToolBox. Can somebody help me?

**Comment by MscrmTools** [comment]
Can you delete (backup fist) your XrmToolBox settings file and see if it works better?

**Comment by kukukeliku** [comment]
You and me both. These fucking retards that coded the XRMToolBox has made something so it can't be opened since whatever update happened since the start of these summer. And I call them retards because they make it impossible to find a fucking e-mail address to report it to, like it'll ever get solved that way.

**Comment by kukukeliku** [comment]
This is all I get when opening this hackish piece of non-quality assured shit:

![image](https://user-images.githubusercontent.com/44030708/46745378-38d9b380-ccad-11e8-86f7-5be2bd438b0a.png)

**Comment by bwmodular** [comment]
@kukukeliku Shame on you.

It's a free open source project, maintained by a small number of volunteers in their own time.
These volunteers have resolved 629 issues and made 1100 commits to the code base since work began.

You don't have to use it, or you could fix it yourself if you are so much better a developer than they are. That's the beauty of open source software.
The software is being used on a daily basis by thousands of users, but because it doesn't work for you, you think it's OK to call the developers fucking retards?
You should be ashamed of yourself if you think this behaviour is acceptable.

**Comment by kukukeliku** [comment]
I don't care. Whatever crap software I write at least OPENS when I double-click it. This doesn't, apart from what Windows supplies it with for the maximize/minimize/close-boxes. And then they don't provide an e-mail address where users can kindly inform about the issue but instead has the users presume that GitHub is the place to post issues on. Keep counting issues and commits, big boy. Myself, I'll be happy when this app unscrews itself and opens like it used to. Yes, I'm a freaking awesome developer. It's why many F500 companies hire me. And that's how I find issues like this and when I finally find where to post these issues, because their websites give a neverending runaround, I do it in a pissed off manner. Uh, yeah, if an application doesn't start and you still release it, are you not retarded by definition? Programs should at least start. I can understand an app crashing while using it. I can't understand releasing an app that doesn't start the way it should.

**Comment by MscrmTools** [comment]
@kukukeliku, following your second comment, if you can see this on your screen, then just click the Maximize button (you see, this little square made for enlarging a window), and you are good to go

**Comment by MscrmTools** [comment]
As for contacting me, if you were so smart, you will have found two twitter accounts, one facebook account and probably an email address somewhere.
There is also a chat on Gitter.
As you can see, there is plenty channels to contact me

**Comment by MscrmTools** [comment]
@Mykel96 Please follow [this procedure](https://www.xrmtoolbox.com/documentation/for-users/reset-xrmtoolbox-installation/)

**Comment by azareei2022** [comment]
> @Mykel96 Please follow [this procedure](https://www.xrmtoolbox.com/documentation/for-users/reset-xrmtoolbox-installation/)

Worked like a charm. Thank you

**Comment by karthikreddi2103** [comment]
Hi @MscrmTools can you please help me in the same i have deleted reinstalled it also not working same error showing for me

Error Time: 2023-05-22 20:39:02.195
System.ArgumentException
Invalid DockState: Content can not be showed as "Unknown" or "Hidden".
WeifenLuo.WinFormsUI.Docking
at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
   at XrmToolBox.New.NewForm..ctor(String[] args)
   at XrmToolBox.Program.Main(String[] args)
