### ISSUE TITLE
Connectivity Issues Dynamics 365 Online

### ISSUE THREAD

**Issue by jjones216** [MscrmTools/XrmToolBox#878]
It appears that a recent Dynamics 365 online update might of broken this plugin.  The plugin just worked a few days ago for me now I am getting the following errors when I click the load metadata button.
<img width="959" alt="NNRelationshipManagerError" src="https://user-images.githubusercontent.com/53379491/61998185-339df780-b07a-11e9-986e-339285092256.png">

**Comment by jjones216** [comment]
I just wanted to add this relates to the Manage NN Relationship plugin only other plugins seem to be working fine.

**Comment by MscrmTools** [comment]
Il will check it tomorrow
Thanks for reporting

**Comment by fberasategui** [comment]
@MscrmTools fyi: it seems there is a new `AttributeMetadata` type, called `FileAttributeMetadata`, however it doesn't seem to be available in the current version of the SDK assemblies. I've raised an [issue](https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/1243) about it, because the published documentation refers to a not-yet-available SDK version.

**Comment by MscrmTools** [comment]
I will release a new version of XrmToolBox today with latest SDK bits. Just hope this one will cover this new FileAttributeMetadata. 
If not, then we will need to wait for new bits

**Comment by jjones216** [comment]
I updated to the latest version of the XRMToolbox this morning and this plugin now appears to be working.  Thanks for the assistance!
