### ISSUE TITLE
WebResource Manager - Missing the root element

### ISSUE THREAD

**Issue by Nyx-Kitsune** [MscrmTools/XrmToolBox#887]
Hi,
when I try to open the plugin display the next message: 
![image](https://user-images.githubusercontent.com/45755023/63342876-e812fc80-c34c-11e9-88c6-eb1334e91b57.png)
I tryed delete this:
c:\users\my_profile\appData\roaming\mscrmtools\xrmtoolbox\settings

The error message persist when Uninstall and install the plugin and XrmToolBox.
How I can get more info of this error?,
thanks.

**Comment by BirgitRD** [comment]
I had the same issue recently.
It turned out the manifest of the plugin was corrupt.
I uninstalled the plugin, manually removed the manifest, and reinstalled the plugin.
After that it worked.
As I use the standard settings, I could find the manifest in C:\Users\<profile>\AppData\Roaming\MscrmTools\XrmToolbox\Settings

**Comment by Nyx-Kitsune** [comment]
Thanks, after that it worked!
