### ISSUE TITLE
Move plugins in a subfolder "Plugins"

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/XrmToolBox#89]
As requested once by Daryl (if I remember well), we can move the plugins assemblies in a subfolder named "Plugins". It will ease to find XrmToolBox.exe in XrmToolBox folder.

I can't tell if this is a breaking change for other plugins or not... especially for those which create their own settings file

Any thought?

**Comment by rappen** [comment]
I think it is a good idea, from a purely cosmetic perspective.
It would of course also affect "installation instructions" where you would have to be clear that the assemblies should be placed in the sub-folder.
Another point is that as long as there is no "installation" for XTB, you would still have to manually delete the files in the XTB folder to enjoy this cleanup.
Regarding the settings file - well, a bit annoying it might be, but not really breaking in that sense (speaking from the use of settings files in my own plugins).

**Comment by MscrmTools** [comment]
I could create a static list of assemblies that are not plugins (this list should not change a lot, I guess) and if I found other assemblies than these ones, I can prompt to delete them or even move only files not already present in Plugins folder in this folder

**Comment by daryllabar** [comment]
That sounds a little dangerous/annoying...  Can't think of any other application that does that.

**Comment by rappen** [comment]
That would of course be a great help for developers like me :+1: 
Perhaps also *.config and *.xml files that you don't recognize...?
But as @daryllabar mentions, might be a bit hazardous...
Is not the time coming to have proper msi (or some other technology) packages?

**Comment by daryllabar** [comment]
I have my own custom config file for maintaining my settings and currently it uses Directory.GetCurrentDirectory() to determine what directory to read and save changes to...  So it wouldn't break anything with that.
Unfortunately I have a sub folder for the CrmSvcUtil, and that is set to be the currentdirectory\cmsvcutil.  So if a user moved everything into a hypothetical plugins directory, it would break.  But then again, if they left it there, it would work fine, and I'd update the location for it in my plugin so that it resides in the Plugins directory... 

If all that happened was the plugin getting moved, I'm not aware of any breaking changes in my code base.  If everything was moved, it would be a breaking change...

**Comment by isultan69** [comment]
I think that users like to use the application with no install file like other ones and that is not a managed crm solution. 

What I really appreciate is to include a vanilla crm class for early binding. I just prefer linq instead of query expression or query by id

**Comment by MscrmTools** [comment]
@rappen @isultan69 You are both correct. We can add an installer but also keep a installer-free version;

Ok, so let's forget about moving automatically plugins. But I can still add a warning popup if I find plugin assemblies in XrmToolBox folder instead of XrmToolBox/Plugins folder

**Comment by daryllabar** [comment]
@isultan69 you're welcome to use mine.  It's in my DLaB.Xrm.dll

**Comment by daryllabar** [comment]
@MscrmTools  sounds like a good compromise.

**Comment by MscrmTools** [comment]
Ok, then! I added this issue for May release to let everybody time to test plugins. As soon as April release is shipped, I will update the source code to use a Plugins subfolder
