### ISSUE TITLE
Problem with Attribute Manager

### ISSUE THREAD

**Issue by scottg78** [MscrmTools/XrmToolBox#914]
We were using Attribute Manager to change a text field to an option set, and the process got an error an quit. The error occurred in the step where the process deletes the old field. It appears that it was checking for dependencies on the old field and got the following error:

System.Exception: Dependencies found

The process then quit. I have attached a text file that contains the log data. This is not an emergency, as we have restored our Dev environment. Just thought I would post it in hopes that the developer would review it and let us know where we made our mistake. We would like to try using it again.

Thank you.

Scott Grimes
[Attribute Manager Log 20190113.txt](https://github.com/MscrmTools/XrmToolBox/files/4055009/Attribute.Manager.Log.20190113.txt)

**Comment by MscrmTools** [comment]
Attribute manager is developed by Daryl LaBar. Please open an issue on his GitHub repo

**Comment by daryllabar** [comment]
The line right above the error gives the clue:

Entity Relationship / Mapping opportunity_originating_lead must be manually removed/added

The tool does not support migrating an Entity Relationship Mapping, so this would have to be done manually, by first copying it down, removing the mapping, then running the tool, then manually recreating the mapping (and since you're changing the type, the type of the other entity's attribute would have to be updated as well.

Also note that none of your data is migrating since it was unable to convert the string to the OptionSetValue, so if it's a requirement that the data is migrated, you may want to create a temp field, migrate the text to the new temp field via a bulk workflow, replace the field with the Attribute Manager, then run another Bulk Workflow to move all the data back, mapping the text value to the appropriate Option set Value

**Comment by scottg78** [comment]
Thank you
