### ISSUE TITLE
Add command line arguments

### ISSUE THREAD

**Issue by shytikov** [MscrmTools/XrmToolBox#92]
Here is an idea for May release.

Add command line arguments handling to XrmToolBox. The goal is to speedup the startup of most common used plugins.

For example, `FetchXMLBuilder` is my everyday tool, and 99% of the cases I'm connecting to organization called `CRMDEV`. It would be much more convenient for me to create desktop shortcut with following command line:
```
XrmToolBox.exe /connection:"CRMDEV" /plugin:"FetchXMLBuilder"
```
As I see it, while showing splash-screen `XTB` asynchronously connects to the given organization, and after establishing it `FetchXMLBuilder` is started.

I believe others also have several plugins and environments that they use most and they would be grateful for such a shortcuts to get them started quicker.

If connection is not set, but plugin is present, `XTB` will just open selected plugin after showing splash-screen.

But we need to keep in mind that #26 is still valid, in case if we have several plugins with the same name there will be vagueness, which plugin should be started.

**Comment by MscrmTools** [comment]
We can think about it I guess.
I'm not sure it is a scenario that will fit majority of users needs but it can be done

As for #26, I will add a comment too

**Comment by drosenba** [comment]
I see that this issue is closed, but was it ever done?  (If so, are there any docs?)

**Comment by shytikov** [comment]
It's implemented, but used for development mostly, as far as I know. Parameters supported are `connection:` and `plugin:` followed by connection and plugin name respectively.

Issues: this functionality should be rewritten to support unique identifiers instead of names.

**Comment by drosenba** [comment]
Thanks...  The problem was that in your example above, the spelling is not exact. 
  /plugin:"FetchXMLBuilder"
should be
  /plugin:"FetchXML Builder"
(with a space in the name)

A nice addition to cmd-line params would be to "run" automated (i.e. batch mode).  That would require that the plugins also look for their args.

**Comment by xi-osman** [comment]
Has this been worked on??

I would find this useful since im creating Web Apps and using the Web Resource Manager. But one issue is for each bug I find it take me time to go on the UI and update web resources would be awesome if i have a command on build that would do something like this.


xrmtoolbox.exe -c devOrg -p WebResourcesPlugin -a "Path:xxxx;Root:xxxx;Overwrite:Yes" 

xrmtoolbox.exe -c "Connection Name" -p "Plugin Name" -a "JSON Formated Arguments sent to Plugin"

If anyone finds this useful I can code this.

**Comment by MscrmTools** [comment]
No.
Any help would be appreciated here. 
I think that would require a new interface to indicate the plugin supports this scenario. 
Then a method to implement to execute the plugin with the arguments.
One point is that plugins are loaded currently from UI events. Not sure how to handle this with a command line approach

**Comment by rappen** [comment]
Thinking out loud here...
We have the MessageBus pattern to call tools from other tools.
Could this not be used to call a tool from the "host" too?
If so, you could simply add the -a flag proposed above.
XTB would connect according to existing feature, it would start the tool according to existing feature, and then send a message to the tool according to existing feature.
The parameters / message to the tool would be limited to a simple string.
Architecture impact would be minimal.
It is entirely up to the tool to handle possible messages.
