### ISSUE TITLE
plagued with exceptions for last 3 years 

### ISSUE THREAD

**Issue by pagex** [MscrmTools/XrmToolBox#942]
Never had a session with XrmToolBox without it throwing one or another exception, got used to it, but now it just non stop: 

Open tool, find Early Bound generator, try delete config path top right corner paste some other path got exception from plugin, hit close got exception from toolbox, then crash.

Plugins library, select one to update say ribbon workbench, says 

This application needs to restart to install updated tools (or new tools that share some files with already installed tools). Click Yes to restart this application now

Yes   No   

Click Yes,  it says about closing window/open tab (had early bound generator open when it failed to load its config error inside xml)  - yes

then Object not set to an instance....

---
- XTB Version: 1.2020.4.38

**Comment by daryllabar** [comment]
Sorry that you're having issues.  Confused as to how you can be having consistent exceptions for 3 years before reporting any thing.  

Lots of questions for you.  Is this error repeatable?  Are there any more error details, like a stack trace?  What is the exception that you're getting from the EBG?  Are you an admin on your machine?  Have you tried a clean reinstall?

**Comment by pagex** [comment]
All steps to reproduce outlined in my fist post, basically if any plugin throws and exception the whole XrmToolBox host crashes, example is early bound generator, open this plugin connect to crm, top right corner there is config path in this plugin cut and paste another path to another xml, plugin crashes, taking toolbox with it. reproduce-able on latest code.

**Comment by MscrmTools** [comment]
Hi @pagex, this behavior is due to the architecture of XrmToolBox itself.
It's not possible in .Net (at least, from my research and test) to have a plugin system that implies UI element to be executed in their own App Domain, with maintaining communication capabilities between plugins.
So this is the responsability of each developer to make sure his plugins don't fail with unexpected exceptions.
There is nothing we can do about this
